apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ansible-chatbot-deploy.yaml
namespace: ansible-chatbot-stack
images:
- name: ansible-chatbot-stack
  newName: quay.io/ansible/ansible-chatbot-stack
  newTag: 0.0.6
- name: ansible-mcp-gateway
  newName: quay.io/ansible/ansible-mcp-gateway
  newTag: 0.0.2
- name: ansible-mcp-controller
  newName: quay.io/ansible/ansible-mcp-controller
  newTag: 0.0.2
- name: ansible-mcp-lightspeed
  newName: quay.io/ansible/ansible-mcp-lightspeed
  newTag: 0.0.2
